spring:
                                                datasource:
                                                  driver-class-name: com.mysql.cj.jdbc.Driver
                                                  username: root
                                                  password: root
                                                  url: jdbc:mysql://localhost:3306/delivery?serverTimezone=UTC
                                                  platform: mysql
                                                  initialization-mode: always
                                                  continue-on-error: true
                                                jpa:
                                                  show-sql: true
                                                  hibernate:
                                                    ddl-auto: create-drop

                                                  database: mysql
                                                  database-platform: org.hibernate.dialect.MySQL57Dialect